spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentdb
    username: root
    password: password


  jpa:
    hibernate:
      ddl-auto: update    # methana update wenuwat create damma parana data store wenne na database eke re-run karankot.
                          # but mulinma DB eka hadakot we must put create.